experiment: "VocoMorphRNN"
notes: "Neural Vocal Modulator V1.0
  RNN & FiLM (Feature-wise Linear Modulation) layers
  are used to condition an audio on an Embedding Vector.
  Input is raw audio
  "
# ------------------------------------------------------------------------------------------------------------------------------ #
config:
  # ------------------------------------------------------------ #
  seed: 13

  data:
    num_workers: 6
    pin_memory: true
    drop_last: true

    channels: 1 # mono/stereo
    sample_rate: &var_sample_rate 16_000
    n_mels: &var_n_mels 80
    n_fft: &var_n_fft 512
    win_length: &var_win_length 512
    hop_length: &var_hop_length 128

    # the chunk of audio the model processes at a time
    frame_length: &var_frame_length 800 # 50ms at 16k
    max_length: 160_000 # 10 sec at 16k sr

    datalists:
      train:
        batch_size: 16
        path: "data/metatadata/train/timit_train.csv"
      valid:
        batch_size: 16
        path: "data/metatadata/train/timit_valid.csv"
      test: 
        batch_size: 16
        path: "data/metatadata/train/timit_test.csv"

    effects:
      &var_modulation_effects [
        "identity_transform",
        "apply_pitch_shift",
        "apply_radio_effect",
        "apply_robotic_effect",
        "apply_scifi_effect",
      ]
  # ------------------------------------------------------------ #
  model:
      chunk_size: *var_frame_length
      overlap: 0
  
      module_stft:
        n_fft: *var_n_fft
        hop_length: *var_hop_length
        win_length: *var_win_length
        output_length: *var_frame_length

      module_effect_encoder:
        effects: *var_modulation_effects
        embedding_dim: &var_embedding_dim 64

      module_rnn_film:
        embedding_dim: *var_embedding_dim
        n_fft: *var_n_fft
        hidden_size: 32
        num_layers: 1
  # ------------------------------------------------------------ #
  # loss functions
  criterions:
    # - name: "EnergyLoss"
    #   weight: 10.0

    - name: "MSELoss"
      weight: 1.0

    - name: "SI_SNRLoss"
      weight: 0.5

    - name: "MultiResolutionSTFTLoss"
      weight: 1.0
      params:
        alpha: 1.0
        beta: 0.5
        resolutions: [
        # Good frequency resolution, medium time resolution
            [1024, 1024, 256],
        # Excellent frequency resolution, poor time resolution
            [2048, 2048, 512],
        # Moderate frequency resolution, good time resolution
            [512, 512, 128],
        ]
    #
    # - name: "STFTLoss"
    #   weight: 0.5
    #   params:
    #     alpha: 0.5
    #     beta: 0.5
    #     n_fft: *var_n_fft
    #     hop_length: *var_hop_length
    #     win_length: *var_win_length
    #
    # - name: "VocalModulationLoss"
    #   weight: 0.7
    #   params:
    #     alpha: 0.5
    #     beta: 0.2
    #     gamma: 0.1
    #     delta: 1.0
    #     sample_rate: *var_sample_rate
    #     n_mels: *var_n_mels
    #     n_fft: *var_n_fft
    #     hop_length: *var_hop_length
    #     win_length: *var_win_length
    #
  # ------------------------------------------------------------ #
  optimizers:
    - name: "AdamW"
      params:
        lr: 5.0e-5
        betas: [0.9, 0.999]
        weight_decay: 1.0e-5
      scheduler:
        name: "ReduceLROnPlateau"
        params:
          mode: "min"
          min_lr: 1.0e-10
          factor: 0.8
          patience: 2
        # name: "WarmupConstantSchedule"
        #   params:
        #     warmup_steps: 1000
  # ------------------------------------------------------------ #
  # metrics to evaluate the model on
  metrics: []
  # ------------------------------------------------------------ #
  trainer:
    max_epoch: 100
    gpuid: [0]
    clip_norm: 5
    start_scheduling: 1
    test_epochs: [1, 10, 25, 50, 75, 100]
    precision: "fp16"
    grad_accumulation_steps: 4

  checkpointer:
    save_interval: 5 # num epochs to save checkpoint
    save_best: true
    keep_last_n: null # null or int
    checkpoint_path: null # checkpoint to load or start from
